### ISSUE TITLE
Implement default content routing selection

### ISSUE THREAD

**Issue by reidlw** [ipfs/roadmap#110]
eta: 2023-06-30

description:
Depends on:

Indexer Double Hashing Support
Spec for Content Routing Selection
Done:

Full support (Kubo + any necessary infrastructure) to support content routing selection, including default use of cid.content by Kubo

**Comment by quickhatche** [comment]
@BigLep checking in on this one, looks like ETA is end of June; does this need to be updated or closed out?

**Comment by BigLep** [comment]
I'm going to close this out.  Not all of this work is done, but this also isn't a focused.

Done: 
* Kubo calls cid.contact by default
* IPNI does double hashing
* Kubo logic for supporting multiple content routers

In progress:
* /routing/v1 double hashing spec: https://github.com/ipfs/specs/pull/421

Not started:
* /routing/v1 double hashing client implementation in Boxo
* /routing/v1 double hashing in Kubo

I'm going to close this as "not planned" since there are clearer tracking items for double hashing support in Kubo: https://github.com/ipfs/kubo/issues/9455
