### ISSUE TITLE
High level notes on prioritization

### ISSUE THREAD

**Issue by tetrisgm** [ipfs/roadmap#36]
I went through the document and was happy to see a push for a single focus. I was however surprised to see **package managers** being the focus. As I kept going through the document, it looked like there was a lot of effort placed on methodology (good thing), but I believe the approach has produced a result that won't pay off in the longer term.

_**Challenges with the current methodology:**_

**1. Prioritization**
The prioritization was made using a matrix of difficulty/ecosystem/importance values. That's solid (though the problem is defining a good set of axes). In this case, the goal was apparently to aim for "bang for buck": finding the lowest hanging fruit with the most value. That's fine, but it's actually a sub-optimal scenario! (tldr: when you optimize for this, longer term projects get pushed back).

I wanted to verify this was indeed the case, and went through the values your team used, and made a little ranking function. Indeed, it showed the ranking you proposed:
![Chart1](https://imgur.com/download/cXI5z7f)
(note: it's also not great to use a column Difficulty where the goal is for the value to be smaller, and the other columns to be smaller).

Part of the justification for the prioritization was some [Github issues](https://github.com/ipfs/notes/issues?q=is%3Aissue+is%3Aopen+label%3A%22package+managers%22). While user feedback is great, it's a pretty iffy way to prioritize a project's strategy: firstly  because the users don't have a full picture of what you're trying to accomplish. Secondly because you would probably find equal amount of requests about other projects (ex: WebOS) if it was an ongoing project. Basically there's a risk of "users asking for a faster horse" because it's what they know.

**2. Long term impact**
The current approach **cannot** deliver most of the 2020+ goals. It will take the better part of a year to deliver end to end package manager, at self-reported  difficulty of 1. There are multiple projects (knowledge via dweb, webos, data web...) that are self-ranked orders of magnitude more difficult. Even if we discount their difficulty because the efforts get easier with time, it's unlikely the goals will be met, unless there's a substantial increase in team size.

_**Proposal:**_
I understand we're entering the second half of the year, and that the package management project is well under way, and switching would create costs. I do think that having this kind of methodology can help get a better sense of how to get the most out of the efforts.

I would recommend thinking about a [Cost of Delay methodology](https://www.leadingagile.com/2017/05/cost-delay-project-management/). Instead of focusing on "What is the most valuable thing, relatively, we could build now?", asking "What would help us capture most value for our goal now?".

I re-did the prioritization and added a column called "Urgency". The idea being "how much compound value can we get from shipping this?". This is somewhere I feel package managers are less impactful than sending large files for example (the former affects IPFS developers marginally, the latter can enable large video platforms to change their infra).
I made some tweaks to the numbers and calculations according to this.
![Chart2](https://imgur.com/download/L0ib8yC)

If all projects can't be delivered end-to-end in a timely manner, and the longer term projects are pushed because they are more risky, how do we solve this?
I don't believe all projects need to be end-to-end to be valuable. I believe they can be versioned, and these smaller steps will help assess their usefulness.

It could very well be that the Sneaker Web is a bad idea, for reasons we don't yet know. Google Glass sure was! The best way to assess this would be a small exploration.

Inversely, working on package managers 100% is likely to yield diminishing results: the last 10% take much more time. By breaking up projects into smaller versions, it'd be possible to get more value with less effort.

I realize this is likely to happen organically, because the team is already making conscious efforts to have a thoughtful methodology. My goal above is to help align with the stated mission of IPFS as fast as possible :)

Happy to talk about this any time before and also at IPFS Camp.

**Comment by momack2** [comment]
Thanks for the note @leshokunin. I appreciate your thoughtful assessment (and that these rankings are difficult to make and require significant thought and discussion). A key understanding from our roadmapping endeavor - and in mapping out so many goals for IPFS - is that each endeavor is not independent and separable. The work done to make Package Managers work effectively on IPFS is the same set of work required to support large files (but with a slightly more technical user base), and much of the performance and updatability needs for the decentralized web, but with a smaller set of UX requirements. That is what we mean by "difficulty" or "delta" in [our sorting function](https://github.com/ipfs/roadmap#ipfs-mission-statement):
> minimal additional requirements and fewer dependencies from the capabilities IPFS has now

And why we sorted by that factor first, before sorting by the other factors (to rerank items tied on "delta") - so that you don't rank goals ahead of intermediate milestones from a technical capability standpoint. In your model, it looks like you're just adding these factors together - which doesn't take into account technical phasing or whether long-term progress or short term importance should be prioritized higher (we chose long term impact).

Your idea of "urgency": 
> how much compound value can we get from shipping this

sounds very similar to the way we defined "ecosystem growth":
> growing our community and resources to help us gravity assist and accelerate our progress

Both seem to describe how valuable it is to onboard a particular goal / user base to the growth rate of the project - though your's may also combine some quality of "impact created" (which we called "importance"). We assessed package managers as having the highest "ecosystem" effect since the community of package creators, users, and registry maintainers globally are well poised to contribute to the value of IPFS, and making this broad community of developers more efficient by using IPFS to solve their problems will create more bandwidth and opportunity for IPFS to be used _by them_ to solve many future problems. Similarly, we saw package managers as being closer in terms of delta/difficulty because the UX is more constrained and the target users more technical - and IPFS still needs to do significant work to be easily usable and configurable by large communities for dweb developers, or end users trying to use it to transfer videos and images. Narrowing in on an intermediate goal lets us separate the end problem space we want to solve into stages, instead of trying to attack all problems at once.

I totally agree with your point about not being able to deliver each goal end to end before moving to the next - this is already something that is clear to us about package managers (our end of year goals are necessarily a subset of the very ambitious [expanded goal for package managers](https://github.com/ipfs/roadmap#2019-goal-expanded)), and we are phasing the work that is required to make progress here, while still building toward the goals we plan to take on in 2020+. Note, the work that we've been doing for Package Managers is largely focused on performance improvements (to adding, providing, and sharing data), especially around large files or large directories. It's also pushed us to address long standing issues around IPNS, MFS, and UnixFS that are critical for package manager usability - but also all sorts of dweb and large file use cases. That's what I mean by the fact that this work isn't separable or independent - to solve the use case we're focused on this year, we are fixing underlying problems applicable and critical to many other use cases as well. However, instead of saying "we have to improve performance...in general" - we have a specific use case, demos, and benchmarks we can run to ensure we're headed in the right direction to meet our specific, intermediate goal.

We have already committed to our priority this year and are seeing useful feedback loops for our working groups and product prioritization by focusing on package managers in particular. That being said, if there are better sorting functions to help prioritize our list of goals - or additional intermediate goals that we should aim for to unlock incremental value while solving tangible problems shared by future goals, including those in our 2020 planning cycle would be great! Happy to brainstorm more at IPFS Camp, or in the weekly Project Working Group meeting when we get closer to planning 2020 priorities (likely in late August).
